# Template to produce a new memcached deployment in OpenShift.
#
# To create an environment from the template, process and apply it:
#   oc process -f memcached-template.yaml | oc apply -f -
---
apiVersion: v1
kind: Template
metadata:
  name: memcached-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: memcached
    name: memcached
  spec:
    tags:
      - annotations: null
        from:
          kind: DockerImage
          name: 'quay.io/redhat-aqe/memcached:latest'
        importPolicy:
          scheduled: true
        name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: memcached
    name: memcached
  spec:
    output:
      pushSecret:
        name: redhat-aqe-memcached-bot-pull-secret
      to:
        kind: DockerImage
        name: quay.io/redhat-aqe/memcached
    runPolicy: Serial
    source:
      git:
        uri: 'https://gitlab.cee.redhat.com/rad/memcached-container.git'
      secrets:
        - secret:
            name: gitlab-auth
      sourceSecret:
        name: gitlab-auth
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: "registry.access.redhat.com/rhel7:latest"
      type: Docker
- apiVersion: v1
  kind: Secret
  type: kubernetes.io/ssh-auth
  data:
    .gitconfig: W2h0dHBdCiAgICAgICAgc3NsVmVyaWZ5PWZhbHNl
    ssh-privatekey: bm9uZQo=
  metadata:
    name: gitlab-auth
